<?php

namespace rednaoeasycalculationforms\core\Managers\HTMLGenerator\HTMLParsers\Templates\FieldSummaryTemplate;

use rednaoeasycalculationforms\core\Managers\HTMLGenerator\HTMLParsers\Core\HTMLParserBase;
use rednaoeasycalculationforms\core\Managers\HTMLGenerator\HTMLParsers\RawHTMLParser;
use rednaoeasycalculationforms\core\Managers\HTMLGenerator\HTMLParsers\Templates\FieldSummaryTemplate\SameAsFormTemplate\SameAsFormTemplate;
use rednaoeasycalculationforms\DTO\FieldSummaryTemplateOptionsDTO;

class FieldSummaryTemplate extends HTMLParserBase
{
    /** @var FieldSummaryTemplateOptionsDTO */
    public $Options;
    public function ParseContent()
    {
        $options=json_decode($this->GetStringAttributeValue('Options'));
        if($options==false||!isset($options->Id))
            return null;

        if($options->Format=="same_as_form")
            return new RawHTMLParser($this->FormBuilder,$this->Parent,null, $this->FormBuilder->ContainerManager->GetHtml($this->GetDocument()->Context));
        else
            return (new OneFieldPerRowTemplate($this->FormBuilder,$this->Parent,$options))->ParseContent();


        return null;
    }

    public function Render()
    {

        return '1'; // TODO: Change the autogenerated stub
    }


    protected function GetTemplateName()
    {
        // TODO: Implement GetTemplateName() method.
    }
}