<?php


namespace rednaoeasycalculationforms\core\Managers\FormManager\Fields;


class FBTotalField extends FBFieldBase
{
    protected function InternalGetHtml($document, $formatter = null)
    {
        return parent::InternalGetHtml($document, $formatter); // TODO: Change the autogenerated stub
    }


    public function GetLineItems()
    {
        $item= parent::GetLineItems()[0];
        $item->Value=$this->GetEntryValue('Value','');
        $item->NumericValue=$this->GetEntryValue('Amount',0);
        return [$item];
    }


}